version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./sqlite.db
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - ./sqlite.db:/app/sqlite.db
    restart: unless-stopped 